baseURL = "/press"
languageCode = "en-us"
title = "presentations"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"
publishDir = "../static/press"

# relativeURLs = true
# uglyURLs = true

[author]
name = "Trim Bresilla"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
# history = true
