baseurl = "/"
title = "bresilla"
theme = "coder"
# theme = "coder-portfolio"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "./docs"

paginate = 20
canonifyurls = true
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses=true

disqusShortname = "kushtrimbresilla"


[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params]
    surname = "Bresilla"
    name = "Trim"
    author = "Trim Bresilla"
    mail = "trim.bresilla@bresilla.com"
    phone = "+38344171997"
    styleaccent = "#ff9000"
    stylebackground = "#080a0f"
    styleforeground = "#c4d0d1"
    gradient = "red, green, blue"

    description = "Personal website & bolg"
    keywords = "blog,developer,personal"
    info = "plant hacker · robotist · reverse engineer"
    avatarurl = "/images/profile_06.jpg"
    cvurl = "/images/profile_02.jpg"
    avatarsvg = "/images/bresilla.svg"
    footercontent = "I solemnly swear that I am up to no good"
    dateformat = "2 January 2006"

    width= "80em"
    hideCredits = false
    hideCopyright = false
    commit = "https://github.com/luizdepra/hugo-coder/tree/"
    rtl = false
    inverted = false
    maxSeeAlsoItems = 5
    custom_css = []
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    unicode = ""
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/bresilla/"
[[params.social]]
    name = "LinkedIn"
    unicode = ""
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/bresilla/"
[[params.social]]
    name = "Twitter"
    unicode = ""
    icon = "fab fa-twitter"
    weight = 4
    url = "https://twitter.com/trimbresilla/"
[[params.social]]
    name = "Youtube"
    unicode = ""
    icon = "fab fa-youtube-square"
    weight = 5
    url = "https://www.youtube.com/channel/UCgx55pjpHgsHwIxexiunA5w?view_as=subscriber"
[[params.social]]
    name = "Reddit"
    unicode = ""
    icon = "fab fa-reddit"
    weight = 6
    url = "https://www.reddit.com/user/bresilla"


[[menu.main]]
    name = "about"
    weight = 1
    url = "about/"

[[menu.main]]
    name = "resume"
    weight = 2
    url = "resume"

[[menu.main]]
    name = "blog"
    weight = 4
    url = "posts/"

[[menu.main]]
    name = "talks"
    weight = 5
    # url = "presentations/"
    url = "talk/"

[params.cv]
    # Contact section
    [params.cv.contact]
        enable = true

        [[params.cv.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: trim.bresilla@bresilla.com"
        title = "trim.bresilla@bresilla.com"

        [[params.cv.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+38344171997"
        title = "+38344171997"

        [[params.cv.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//bresilla.com"
        title = "bresilla.com"

        [[params.cv.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/bresilla"
        title = "linkedin.com/in/bresilla"

        [[params.cv.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/bresilla"
        title = "github.com/bresilla"

        [[params.cv.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/trimbresilla"
        title = "@trimbresilla"

    # Education section
    [params.cv.education]
        enable = true
        icon = "fa-university"
        title = "Education"

        [[params.cv.education.list]]
        degree = "MSc in Computer Science"
        college = "University of London"
        dates = "2006 - 2010"

        [[params.cv.education.list]]
        degree = "BSc in Applied Mathematics"
        college = "Bristol University"
        dates = "2007 - 2011"

    # Languages section
    [params.cv.language]
        enable = true
        icon = "fa-language"
        title = "Languages"

        [[params.cv.language.list]]
        language = "Albanian"
        level = "Native"

        [[params.cv.language.list]]
        language = "English"
        level = "Professional"

        [[params.cv.language.list]]
        language = "Italian"
        level = "Good"

        [[params.cv.language.list]]
        language = "German"
        level = "Good"

    # Interests section
    [params.cv.interests]
        enable = true
        icon = "fa-gamepad"
        title = "Interests"

        [[params.cv.interests.list]]
        interest = "Climbing"

        [[params.cv.interests.list]]
        interest = "Snowboarding"

        [[params.cv.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.cv.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Technology is making changes in our everyday life. It is changing the way on how and what we think of occupation/work. Agriculture as the oldest and most fundamental occupation, is seeing the greatest change of all. New techniques, as a result of new technological achievements in AI and Robotics, have become the new standard. I envision myself becoming one of many people that are making this change possible, and my skills both in Agriculture sciences and Computer engineering put me right in the center of those changes."

    # Experiences section
    [params.cv.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.cv.jobs.list]]
        position = "Lead Developer"
        dates = "2015 - Present"
        company = "Startup Hubs, San Francisco"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

        [[params.cv.jobs.list]]
        position = "Senior Software Engineer"
        dates = "2014 - 2015"
        company = "Google, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.cv.jobs.list]]
        position = "UI Developer"
        dates = "2012 - 2014"
        company = "Amazon, London"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

    # Projects section
    [params.cv.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.cv.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.cv.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.cv.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.cv.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.cv.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.cv.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.cv.skills.list]]
        skill = "Python & Django"
        level = "98%"

        [[params.cv.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[params.cv.skills.list]]
        skill = "Angular"
        level = "95%"

        [[params.cv.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[params.cv.skills.list]]
        skill = "Ruby on Rails"
        level = "75%"

        [[params.cv.skills.list]]
        skill = "Sketch & Photoshop"
        level = "60%"
